### ISSUE TITLE
How to train with multiple GPU?

### ISSUE THREAD

**Issue by CookieLau** [y2l/meta-transfer-learning#4]
Thanks for your noval contribution first !
I want to know if there is any way to train model with multiple GPU together ?

**Comment by y2l** [comment]
Thanks for your interest in our work.
In order to run this repo on multiple GPUs, you need to change the code as the following guide: [https://www.tensorflow.org/guide/using_gpu#using_multiple_gpus](https://www.tensorflow.org/guide/using_gpu#using_multiple_gpus).
